Add iwyu, clang-format checks to CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -12,3 +12,32 @@ jobs:
         submodules: true
     - name: make
       run: make -j -C src
+
+  code_health_checks:
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v4
+    - name: Install tools
+      run: |
+        sudo apt update
+        sudo apt -q install clang-format iwyu
+    - name: Run checks
+      run: |
+        make -C src fixincludes
+        make -C src format
+        git diff > formatting-fixes.diff
+        if ! grep "" formatting-fixes.diff; then
+          rm -f formatting-fixes.diff
+        else
+          (echo "Formatting errors detected by clang-format. Please run" \
+                "\`make fixincludes && make format\` or apply" \
+                "formatting-fixes.diff below.";
+           echo) >> $GITHUB_STEP_SUMMARY
+          false
+        fi
+    - uses: actions/upload-artifact@v4
+      if: '!cancelled()'
+      with:
+        if-no-files-found: ignore
+        name: formatting-fixes.diff
+        path: formatting-fixes.diff
